# Generated by Django 3.1.7 on 2022-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inner_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_fonts', models.CharField(default='', max_length=150)),
                ('header_up_down', models.FloatField(default=0)),
                ('header_left_right', models.FloatField(default=0)),
                ('font_inc_dec', models.FloatField(default=0)),
                ('digit_number_font', models.CharField(default='', max_length=150)),
                ('numbering_font_size', models.FloatField(default=10.0)),
                ('numbering_up_down', models.FloatField(default=0.0)),
                ('numbering_left_right', models.FloatField(default=0.0)),
                ('digit_font_size', models.FloatField(default=16.0)),
                ('digit_left_right', models.FloatField(default=0.0)),
                ('digit_up_down', models.FloatField(default=0.0)),
                ('digit_space', models.FloatField(default=0.0)),
                ('front_inc', models.FloatField(default=0.0)),
                ('prob_per_row', models.IntegerField(default=0)),
                ('prob_per_col', models.IntegerField(default=0)),
                ('length_of_digit', models.IntegerField(default=0)),
                ('ractangle_up_down', models.FloatField(default=0.0)),
                ('ractangle_left_right', models.FloatField(default=0.0)),
                ('rec_l_r_inc', models.FloatField(default=0.0)),
                ('rec_u_d_inc', models.FloatField(default=0.0)),
                ('rec_on_off', models.FloatField(default=0.0)),
                ('line_inc', models.FloatField(default=0.0)),
                ('line_up_down', models.FloatField(default=0.0)),
                ('line_left_right', models.FloatField(default=0.0)),
                ('ineer_space', models.FloatField(default=0.0)),
            ],
        ),
    ]
