# Generated by Django 3.1.7 on 2022-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inner_page',
            name='digit_number_font',
            field=models.CharField(default='Helvetica-Bold', max_length=150),
        ),
        migrations.AlterField(
            model_name='inner_page',
            name='header_fonts',
            field=models.CharField(default='Helvetica-Bold', max_length=150),
        ),
    ]
