# Generated by Django 3.1.7 on 2022-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0002_auto_20220619_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inner_page',
            name='length_of_digit',
            field=models.IntegerField(default=1),
        ),
    ]
