# Generated by Django 3.1.7 on 2022-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0003_auto_20220619_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='inner_page',
            name='number_on_off',
            field=models.IntegerField(default=1),
        ),
    ]
