# Generated by Django 4.0.4 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0005_auto_20220620_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inner_page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
