# Generated by Django 3.1.7 on 2022-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordsearch_inner_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(default='Helvetica-Bold', max_length=150)),
                ('word_font_size', models.FloatField(default=10.0)),
                ('word_up_down', models.FloatField(default=0.0)),
                ('word_left_right', models.FloatField(default=0)),
                ('word_left_right_space', models.FloatField(default=0)),
                ('word_up_down_space', models.FloatField(default=0)),
                ('alphabate_font_size', models.FloatField(default=10.0)),
                ('alphabate_up_down', models.FloatField(default=0.0)),
                ('alphabate_left_right', models.FloatField(default=0.0)),
                ('alphabate_left_right_space', models.FloatField(default=0)),
                ('alphabate_up_down_space', models.FloatField(default=0)),
                ('row', models.IntegerField(default=5)),
                ('column', models.IntegerField(default=5)),
            ],
        ),
    ]
