# Generated by Django 3.1.7 on 2022-07-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='rectangle_l_r',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='rectangle_u_d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='alphabate_font_size',
            field=models.FloatField(default=16.0),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_font_size',
            field=models.FloatField(default=16.0),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_left_right',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_up_down',
            field=models.FloatField(default=9.0),
        ),
    ]
