# Generated by Django 3.1.7 on 2022-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0003_auto_20220717_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='number_show',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='numbering_left_right',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='numbering_up_down',
            field=models.FloatField(default=9.0),
        ),
    ]
