# Generated by Django 3.1.7 on 2022-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0004_auto_20220717_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='number_show',
            field=models.IntegerField(default=0),
        ),
    ]
