# Generated by Django 3.1.7 on 2022-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0005_auto_20220717_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='problem_per_page',
            field=models.IntegerField(default=1),
        ),
    ]
