# Generated by Django 3.1.7 on 2022-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0006_wordsearch_inner_page_problem_per_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='puzzleoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_option', models.IntegerField(default=1)),
            ],
        ),
    ]
