# Generated by Django 3.1.7 on 2022-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0007_puzzleoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='line_left_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='line_up_down',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='alphabate_font_size',
            field=models.FloatField(default=18.5),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='column',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='number_show',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='numbering_left_right',
            field=models.FloatField(default=3.84),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='numbering_up_down',
            field=models.FloatField(default=10.12),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='rectangle_l_r',
            field=models.FloatField(default=-0.09),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='rectangle_u_d',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='row',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_font_size',
            field=models.FloatField(default=13.7),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_left_right',
            field=models.FloatField(default=1.8),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_left_right_space',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='word_up_down',
            field=models.FloatField(default=5.0),
        ),
    ]
