# Generated by Django 3.1.7 on 2022-07-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0009_auto_20220718_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='numbering_font_size',
            field=models.FloatField(default=18.5),
        ),
    ]
