# Generated by Django 3.1.7 on 2022-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0010_wordsearch_inner_page_numbering_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='puzzle_up_down',
            field=models.FloatField(default=5.0),
        ),
    ]
