# Generated by Django 3.1.7 on 2022-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0011_wordsearch_inner_page_puzzle_up_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearch_inner_page',
            name='right_puzzle',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='wordsearch_inner_page',
            name='puzzle_up_down',
            field=models.FloatField(default=-5.0),
        ),
    ]
