# Generated by Django 3.2.8 on 2021-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20211011_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_file',
            name='file_upload',
            field=models.FileField(upload_to='model/file'),
        ),
    ]
