# Generated by Django 4.0.4 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20220619_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
